# Generated by Django 6.0.4 on 2026-06-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_checker', '0005_more_seed_data'),
        ('theory', '0002_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='related_tasks', to='theory.article'),
        ),
    ]
