# Generated by Django 6.0.4 on 2026-06-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_checker', '0006_task_related_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='verification_query',
            field=models.TextField(blank=True, help_text='SELECT-запрос для проверки DDL/DML задач (выполняется после запроса пользователя)'),
        ),
    ]
